# Generated by Django 5.1.4 on 2025-01-22 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Eléctrico', 'Eléctrico')], default='Gasolina', max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen_1', models.ImageField(upload_to='productos/')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_4', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_5', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('video_url', models.CharField(max_length=200)),
                ('cantidad_me_gusta', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('enlace_detalles', models.URLField(blank=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No disponible', 'No disponible'), ('En arriendo', 'En arriendo'), ('Para Importar', 'Para Importar')], default='Disponible', max_length=20)),
                ('categoria', models.CharField(choices=[('Venta', 'Venta'), ('Arriendo', 'Arriendo')], default='Venta', max_length=50)),
                ('procesos', models.CharField(choices=[('GRUA HORQUILLA', 'Grua Horquilla'), ('ALZA HOMBRE', 'Alza Hombre'), ('BRAZO ARTICULADO', 'Brazo Articulado'), ('PLATAFORMA DE ELEVACION', 'Plataforma de Elevación')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAlzaHombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Alza Hombre',
                'verbose_name_plural': 'Tipos de Alza Hombres',
            },
        ),
        migrations.CreateModel(
            name='TipoBrazoArticulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Brazo Articulado',
                'verbose_name_plural': 'Tipos de Brazos Articulados',
            },
        ),
        migrations.CreateModel(
            name='TipoGruaHorquilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Grua Horquilla',
                'verbose_name_plural': 'Tipos de Gruas Horquillas',
            },
        ),
        migrations.CreateModel(
            name='TipoPlataformaDeElevacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Plataforma de Elevación',
                'verbose_name_plural': 'Tipos de Plataformas de Elevación',
            },
        ),
        migrations.CreateModel(
            name='AlzaHombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(choices=[('Diesel', 'Diesel'), ('Bencina', 'Bencina'), ('Eléctrico', 'Eléctrico')], max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tamaño', models.CharField(max_length=50)),
                ('potencia_compactacion', models.CharField(max_length=50)),
                ('kilowatts', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.tipoalzahombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrazoArticulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(choices=[('Diesel', 'Diesel'), ('Bencina', 'Bencina'), ('Eléctrico', 'Eléctrico')], max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('capacidad', models.CharField(max_length=50)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.tipobrazoarticulado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GruaHorquilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(choices=[('Diesel', 'Diesel'), ('Bencina', 'Bencina'), ('Eléctrico', 'Eléctrico')], max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('profundidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.tipogruahorquilla')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlataformaDeElevacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(choices=[('Diesel', 'Diesel'), ('Bencina', 'Bencina'), ('Eléctrico', 'Eléctrico')], max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('capacidad', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=50)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.tipoplataformadeelevacion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
